# Generated by Django 3.1 on 2023-09-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20230925_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
